# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRentalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('lent_from', models.DateTimeField(auto_now_add=True)),
                ('scheduled_lent_to', models.DateTimeField(auto_now_add=True)),
                ('lent_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
