# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('category', models.IntegerField(max_length=3)),
                ('author', models.CharField(max_length=255)),
                ('editor', models.CharField(max_length=255)),
                ('translator', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publishedDate', models.DateTimeField()),
                ('edition', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('registerTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name_kana', models.CharField(max_length=10)),
                ('first_name_kana', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='bookrentalstatus',
            name='lent_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookrentalstatus',
            name='lent_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookrentalstatus',
            name='scheduled_lent_to',
            field=models.DateTimeField(),
        ),
    ]
